# This is a basic workflow to help you get started with Actions

name: 'CI: PR to master branch'

# Controls when the workflow will run
on: { pull_request: { branches: [ main, master ] } }

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ github.event.pull_request.title }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport

      - name: Check coverage and publish
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ./${{ github.event.pull_request.title }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      - name: Discover used languages
        id: discover
        run: |
          if [[ -d "src/main/java" ]]; then
            echo "java=true" >> $GITHUB_OUTPUT
          else
            echo "java=false" >> $GITHUB_OUTPUT
          fi

          if [[ -d "src/main/kotlin" ]]; then
            echo "kotlin=true" >> $GITHUB_OUTPUT
          else
            echo "kotlin=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate javadoc
        if: ${{ steps.discover.outputs.java == 'true' }}
        run: ./gradlew javadoc

      - name: Publish javadoc
        if: ${{ steps.discover.outputs.java == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: ${{ github.event.pull_request.title }}/build/docs/javadoc
          target-folder: ${{ github.event.pull_request.title }}

      - name: Generate dokka
        if: ${{ steps.discover.outputs.kotlin == 'true' }}
        run: ./gradlew dokkaHtml

      - name: Publish dokka
        if: ${{ steps.discover.outputs.kotlin == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: ${{ github.event.pull_request.title }}/build/dokka/html
          target-folder: ${{ github.event.pull_request.title }}

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: '.github/google_checks.xml'
          reporter: 'github-pr-check'
